#!/bin/sh
#xrandr --output eDP-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output HDMI-1 --off
xrandr --output eDP --primary --mode 1920x1200 --pos 0x0 --rotate normal --brightness 0.7 --output DisplayPort-1 --off
