#!/bin/sh
#xrandr --output eDP-1 --primary --mode 1366x768 --pos 1920x197 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal
xrandr --output eDP --primary --mode 1920x1200 --pos 1920x197 --rotate normal --brightness 0.7 --output DisplayPort-1 --mode 1920x1080 --pos 0x0 --rotate normal --brightness 0.9
