inoremap fd <ESC>
vnoremap fd <ESC>
inoremap <C-f> <Right>
inoremap <C-b> <Left>
inoremap <C-d> <Del>
inoremap <C-h> <BS>
inoremap <C-a> <C-o>^
inoremap <C-e> <C-o>$
inoremap <C-n> <Down>
inoremap <C-p> <Up>
vnoremap . :norm.<CR>
set history=200
set number
set noswapfile
set hlsearch
set ignorecase
set incsearch
syntax on
