if [[ $(uname -s) == "Darwin" ]]; then
  [[ -d /opt/homebrew/bin ]] && eval "$(/opt/homebrew/bin/brew shellenv)"
  if [[ -d /usr/local/opt/openjdk/bin ]]; then export PATH="/usr/local/opt/openjdk/bin:$PATH"; fi
fi

[[ ! -d ~/.zprofile.d ]] && mkdir ~/.zprofile.d
if [ "$(ls -A ~/.zprofile.d )" ]; then
  for file in ~/.zprofile.d/*
  do
    source $file
  done
fi
