# https://checkoway.net/musings/nix/
# might be necessary only for zsh, not bash
if [[ $(uname -s) == "Darwin" ]]; then
  [[ -o login ]] && export PATH='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'

  if [[ -f '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]]; then
    source '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
    # already in zshrc
    #export NIX_PATH="$HOME/.nix-defexpr"
  fi
fi
