# https://checkoway.net/musings/nix/
# might be necessary only for zsh, not bash
# this was added for Nix, but might be good to keep
if [[ $(uname -s) == "Darwin" ]]; then
  [[ -o login ]] && export PATH='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
fi
