## p10k

# Enable Powerlevel10k instant prompt. (Should stay close to) the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

## zplug

source ~/.zplug/init.zsh

zplug "agkozak/zsh-z"
zplug "lib/completion", from:oh-my-zsh
zplug "lib/key-bindings", from:oh-my-zsh
zplug "romkatv/powerlevel10k", as:theme, depth:1
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# os specific bits

function debian_zshrc {
    alias editsrc="sudo vim /etc/apt/sources.list"
    export PATH="/home/mario/.local/bin:$PATH"
}
[[ $(uname -s) == "Linux" ]] && debian_zshrc

# path

export PATH="$HOME/bin:$PATH"
alias path="echo $PATH | tr  ':'  '\n' | nl"

# history
setopt hist_expire_dups_first # When trimming history, lose oldest duplicates first
setopt hist_ignore_all_dups # Do not write events to history that are duplicates of previous events
setopt hist_ignore_space # Remove command line from history list when first character on the line is a space
setopt hist_reduce_blanks # Remove extra blanks from each command line being added to history
setopt share_history # Imports new commands and appends typed commands to history

HISTFILE="$HOME/.zsh_history"
HISTSIZE=25000
SAVEHIST=25000
[[ ! -f $HISTFILE ]] && touch $HISTFILE

## aliases

# aws-cli
alias awsco="vim ~/.aws/config"
alias awscr="vim ~/.aws/credentials"

# git
alias g="git status"
alias ga="git add"
alias gaa="git add ."
alias gai="git add -p"
alias gb="git checkout"
alias gbl="git branch --list"
alias gbn="git checkout -b"
alias gb-default-name="git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'"
alias gbm="gb-default-name | xargs git checkout && git pull --rebase"
alias gc="git commit -m"
alias gca="git commit --amend"
alias gcan="gca --no-edit"
alias gaca="gaa && gca"
alias gacan="gaa && gcan"
alias gcl="git clone"
alias gco="git checkout ."
alias gac="gaa && gc"
alias gd="git diff"
alias gclean="git restore . && git clean -df"
alias gdca="git diff --cached"
alias gdco="git diff --color-words"
alias gp="git push --force-with-lease"
alias gpf="git push --force"
alias gl="git log"
alias gnuke="git clean -fdx"
alias gpl="git pull"
alias greb="git pull --rebase"
alias grem="git remote -v"
alias gunst="git restore --staged ."
alias gs="git show"
alias gsh="git show HEAD"
alias gst="git stash -u"
alias gstn="git stash save -u"
alias gstp="git stash pop"
alias gundos="git reset --soft HEAD^"
alias gundoh="git reset --hard HEAD^"

alias sshco="vim ~/.ssh/config"

# emacs
alias em="cd ~/.emacs.d"
alias sm="cd ~/spacemacs"
function ep {
  if [[ $(uname -s) == "Darwin" ]]; then
    open -a "Emacs" --args --chdir $PWD --with-profile "$@"
  else
    emacs --with-profile $1 & disown
  fi
}

alias rr="ranger"

# terraform
alias tf="terraform fmt"
alias tg="terraform get"
alias th="terraform --help"
alias ti="terraform init"
alias tp="terraform plan"
alias ts="terraform state show"
alias tsl="terraform state list"
alias tv="terraform version"

# zsh
alias sz="source ~/.zshrc"
alias szp="source ~/.zprofile"
alias zp="vim ~/.zprofile"
alias zs="vim ~/.zshrc"

# directory navigation
setopt auto_cd

alias -- -="cd -"
alias -- ~="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

for file in ~/.zshrc.d/*
do
  source $file
done

# nix
if [ -e /home/mario/.nix-profile/etc/profile.d/nix.sh ]; then . /home/mario/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
#export NIX_PATH="$HOME/.nix-defexpr/channels"
# HOME MANAGER /home/mario/.config/home-manager/home.nix
